import streamlit as st
import pandas as pd
import lasio
import io
import os

def convert_depth_units(df, depth_column, from_unit, to_unit):
    if from_unit == to_unit or from_unit in ['index', 'unknown'] or to_unit in ['index', 'unknown']:
        return df

    METERS_TO_FEET = 3.28084
    FEET_TO_METERS = 1 / METERS_TO_FEET
    df_converted = df.copy()

    if from_unit.lower() in ['m', 'meters', 'metres'] and to_unit.lower() in ['ft', 'feet']:
        df_converted[depth_column] *= METERS_TO_FEET
    elif from_unit.lower() in ['ft', 'feet'] and to_unit.lower() in ['m', 'meters', 'metres']:
        df_converted[depth_column] *= FEET_TO_METERS
    else:
        st.warning(f"⚠️ Unsupported unit conversion: {from_unit} to {to_unit}.")
    return df_converted

def combine_dataframes(selected_curves, logical_file_dfs, export_unit):
    if not selected_curves:
        return None

    dfs_to_combine = {}
    depth_columns = {}
    for curve_info in selected_curves:
        key = curve_info['logical_file_key']
        curve = curve_info['curve']
        depth_col = curve_info['depth_column']
        depth_unit = curve_info['depth_unit']

        if key in logical_file_dfs:
            if key not in dfs_to_combine:
                df = logical_file_dfs[key][[depth_col, curve]].copy()
                df = convert_depth_units(df, depth_col, depth_unit, export_unit)
                dfs_to_combine[key] = df
                depth_columns[key] = depth_col
            else:
                dfs_to_combine[key][curve] = logical_file_dfs[key][curve]

    if not dfs_to_combine:
        st.error("❌ No valid data available for export.")
        return None

    reference_key = list(dfs_to_combine.keys())[0]
    reference_df = dfs_to_combine[reference_key]
    combined_df = reference_df.rename(columns={depth_columns[reference_key]: 'DEPTH'})

    for key, df in dfs_to_combine.items():
        if key == reference_key:
            continue
        df = df.rename(columns={depth_columns[key]: 'DEPTH'})
        combined_df = pd.merge(combined_df, df, on='DEPTH', how='outer')

    return combined_df

def create_las_file(df, curves, depth_column='DEPTH', depth_unit='unknown'):
    las = lasio.LASFile()
    las.well.WELL.value = "WELL"
    las.other = f"Depth unit: {depth_unit}\nGenerated by DLIS InfoView"

    if depth_column in df.columns:
        las.append_curve_item(lasio.CurveItem(mnemonic=depth_column, unit=depth_unit, data=df[depth_column]))
    else:
        st.error(f"⚠️ Depth channel '{depth_column}' not found.")
        return None

    for curve in curves:
        if curve in df.columns and curve != depth_column:
            las.append_curve_item(lasio.CurveItem(mnemonic=curve, unit='', data=df[curve]))

    buffer = io.StringIO()
    las.write(buffer, version=2.0)
    buffer.seek(0)
    return buffer.getvalue().encode('utf-8')

def export():
    st.markdown("## 💾 Export Selected Curves to LAS")
    st.markdown("Create a LAS file from your selected log curves with clean formatting and unit control.")
    st.markdown("---")

    if 'selected_curves' not in st.session_state or not st.session_state.selected_curves:
        st.warning("⚠️ No curves selected. Please select curves in the Data Visualization page.")
        return

    if 'logical_file_dfs' not in st.session_state:
        st.warning("⚠️ Frame data not available. Go to the visualization page to load frames.")
        return

    st.markdown("### 📋 Selected Curves")
    for i, curve_info in enumerate(st.session_state.selected_curves):
        col1, col2, col3 = st.columns([4, 4, 1])
        with col1:
            st.markdown(f"**🔹 {curve_info['curve']}**")
            st.markdown(f"*Logical File:* `{curve_info['logical_file']}`  \n*Frame:* `{curve_info['frame']}`")
        with col2:
            st.markdown(f"*Depth:* `{curve_info['depth_column']}` ({curve_info['depth_unit']})")
        with col3:
            if st.button("🗑️ Remove", key=f"remove_{i}"):
                st.session_state.selected_curves.pop(i)
                st.success("Removed successfully!")
                st.rerun()

    if not st.session_state.selected_curves:
        st.info("📭 No curves remaining. Return to previous page to add curves.")
        return

    st.markdown("### 📐 Select Export Unit")
    export_unit = st.selectbox("Choose depth unit for LAS export:",
                               options=['m (meters)', 'ft (feet)'])
    export_unit_short = export_unit.split()[0]

    st.markdown(f"**🧱 DEPTH** will be included automatically in `{export_unit_short}`.")

    combined_df = combine_dataframes(
        st.session_state.selected_curves,
        st.session_state.logical_file_dfs,
        export_unit_short
    )

    if combined_df is None:
        return

    # Filename input
    st.markdown("### 📝 Output File Name")
    default_filename = "output.las"
    if 'uploaded_file_name' in st.session_state:
        default_filename = os.path.splitext(st.session_state.uploaded_file_name)[0] + ".las"

    file_name = st.text_input("Enter LAS file name:", default_filename)

    # Download button
    try:
        curves_to_export = [curve_info['curve'] for curve_info in st.session_state.selected_curves]
        las_bytes = create_las_file(combined_df, curves_to_export, depth_column='DEPTH', depth_unit=export_unit_short)

        if las_bytes:
            st.download_button(
                label="📥 Download LAS File",
                data=las_bytes,
                file_name=file_name,
                mime="application/octet-stream"
            )
    except Exception as e:
        st.error(f"❌ Error generating LAS file: {e}")
